plugins {
    id 'java'
    id 'io.qameta.allure' version '4.2.0'
}

group = 'org.example'
version = '1.0-SNAPSHOT'

repositories {
    mavenCentral()
}

def allureVersion = "2.24.0"

dependencies {
    testImplementation platform('org.junit:junit-bom:5.10.0')
    testImplementation 'org.junit.jupiter:junit-jupiter'
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
    testImplementation 'org.junit.jupiter:junit-jupiter-params'
    testImplementation 'org.assertj:assertj-core:3.27.7'
    implementation 'io.rest-assured:rest-assured:5.5.6'
    implementation 'com.fasterxml.jackson.core:jackson-databind:2.17.0'
    implementation 'com.fasterxml.jackson.datatype:jackson-datatype-jdk8:2.17.0'
    implementation 'org.seleniumhq.selenium:selenium-java:4.43.0'
    testImplementation 'com.codeborne:selenide:7.17.0'

    // Allure адаптеры
    testImplementation "io.qameta.allure:allure-jupiter:${allureVersion}"
    testImplementation "io.qameta.allure:allure-selenide:${allureVersion}"
    testImplementation "io.qameta.allure:allure-rest-assured:${allureVersion}"
    testImplementation "io.qameta.allure:allure-assertj:${allureVersion}"

}

// Настройка Allure плагина
allure {
    version = '2.24.0'
}

tasks.withType(Test) {
    testClassesDirs = sourceSets.test.output.classesDirs
    classpath = sourceSets.test.runtimeClasspath
}

test {
    useJUnitPlatform()
    outputs.upToDateWhen { false }
}

// Задание №1. Запуск всех тестов
tasks.register("runAllTests", Test) {
    group = 'my_tests'
    description = 'RUN ALL TESTS'
    outputs.upToDateWhen { false }
    useJUnitPlatform {
        include '**/AllTasksTest.class'
    }
}

tasks.register("finalReport") {
    group = 'my_tests'
    description = 'Выводит отчет после прогона тестов'
    dependsOn('runAllTests')
    doLast {
        println("Test run is over")
    }
}

tasks.register("runRandomValuesTasks", Test) {
    group = 'my_tests'
    outputs.upToDateWhen { false }
    useJUnitPlatform {
        include '**/RandomValuesTasksTest.class'
    }
    doLast {
        println("Test run is over!")
    }
}

tasks.register("ShortTest", Test) {
    group = 'my_tests'
    description = 'Run tests with tags ShortTest'
    outputs.upToDateWhen { false }
    useJUnitPlatform {
        includeTags 'ShortTest'
    }
}

tasks.register("apiTest", Test) {
    group = 'my_tests'
    description = 'Run tests for API'
    outputs.upToDateWhen { false }
    useJUnitPlatform {
        include '**/api/api_tests/GoodTest.class'
    }
}

tasks.register("runSeleniumTests", Test) {
    group = 'my_tests'
    description = 'Run Selenium tests'
    outputs.upToDateWhen { false }
    useJUnitPlatform {
        include '**/ui/SeleniumTest/**/*.class'
    }
    doLast {
        println("!!! SELENIUM TESTS RUN IS OVER !!!")
    }
}

tasks.register("runSelenideTests", Test) {
    group = 'my_tests'
    description = 'RUN SELENIDE TESTS'
    outputs.upToDateWhen { false }
    useJUnitPlatform {
        include '**/ui/SelenideTest/**/*.class'
    }
    doLast {
        println("!!! SELENIDE TESTS RUN IS OVER !!!")
    }
}

tasks.register("runApiUiTests") {
    group = 'my_tests'
    description = 'Прогон API и Selenide тестов'
    dependsOn('apiTest')
    dependsOn('runSelenideTests')
    doLast {
        println("API and UI tests is over!!!")
    }
}
runSelenideTests.mustRunAfter('apiTest')


